### ISSUE TITLE
cross-domain compatibility message

### ISSUE THREAD

**Issue by darkn3rd** [ehearty/Swadl#11]
I am trying to use Artifactory's Jersey generated, which from the server is: http://server:port/artifactory/api/application.wadl.  This is referenced https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API.

I downloaded the file, and edited the xmlDoc to point to a file I named at artifactory.wadl.  And I get the following error:
```
Unable to load wadl. Check cross-domain compatibility.
```

I noticed the downloaded wadl references, has this: 
```
<resources base="http://172.16.0.48:8081/artifactory/api/">
```

Is this the cause of the probelm.  172.16.0.48 is IP running from my vagrant box running artifactory.

**Comment by ehearty** [comment]
The host and port of Swadl has to be the same as that of the wadl, or
you'll run into cross domain compatibility issues.

If you downloaded the wadl, however, and are running it on the same host as
Swadl, then it's possible there's something else going on. If you're
comfortable sending me the the documents, I can take a look.

Thanks,
Elena

On Fri, Mar 31, 2017 at 12:24 PM, Joaquin Menchaca <notifications@github.com

**Comment by ehearty** [comment]
Closing as I haven't received a response.
